### ISSUE TITLE
does this statement should be ((bitCount>>dimension)&1)?

### ISSUE THREAD

**Issue by Nervous-** [hypro/hypro#20]
https://github.com/hypro/hypro/blob/bcf527ebe3665f385b6f88e744061a4df43feae6/src/hypro/representations/Box/Box.tpp#L242

does the function really return all the permutaions ?

**Comment by hypro** [comment]
Theoretically it should, yes. An explanation of my thoughts: Each vertex of a box can (per dimension) only have the coordinate corresponding to the lower or to the upper bound of the according interval. We want to get all 2^d possible combinations, which corresponds to all numbers up to 2^d in binary format.

Example: 3-D box, which has 2^3 = 8 vertices. For each dimension 0,1,2 we need to take the lower and the upper bound -> 8 combinations. We chose (in binary) 1 to indicate that the upper bound should be taken and 0 to indicate that the lower bound should be taken. Then we enumerate all numbers from 0 up to 8-1 in binary, because this makes sure we get all possible combinations, i.e. 000 is the lowest vertex in the box, 111 the highest, 010 for instance refers to the vertex built from taking the lower bound for dimension 0, the upper for dim. 1 and the lower from dim. 2 and so on.

Does this help?

**Comment by Nervous-** [comment]
thank you for your response, i just write another  demo to test this section, it does return all the combinations. it should be my mistake when i was test this section the first time. really sorry for opening this issue.

and i have another question about the project, it still does not yet support non-linear system ? right?
does this  schedualed ?

**Comment by hypro** [comment]
Uhm, I've worked on generalizing some datastructures which is needed to be able to analyze non-linear systems as well, but right now there is no concrete schedule for this. We are aware that this might be interesting for some people, I can notify you, if there is further development.

**Comment by Nervous-** [comment]
ok, thank you. :) good job!
